name: quality gates
on:
  workflow_dispatch:
    inputs:
      battle:
        description: 'The battle number'
        required: true
        type: number
      task:
        description: 'The task number'
        required: true
        type: boolean
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: yarn install
      - name: test
        run: npx jest src/${{ inputs.battle }}/${{ inputs.task }}.js
